import React, { useEffect, useRef } from 'react';
import mermaid from 'mermaid';
import { Network } from 'lucide-react';

export default function VisualStudio({ diagram, settings }) {
  const elementRef = useRef(null);

  useEffect(() => {
    let isMounted = true;
    
    if (elementRef.current && diagram) {
      const isDark = document.documentElement.classList.contains('dark');
      try {
        mermaid.initialize({
          startOnLoad: false,
          theme: 'base',
          themeVariables: {
            primaryColor: isDark ? '#1e293b' : '#f1f5f9', // zinc-800 vs zinc-100
            primaryTextColor: isDark ? '#f8fafc' : '#0f172a',
            primaryBorderColor: isDark ? '#334155' : '#e2e8f0',
            lineColor: isDark ? '#60a5fa' : '#3b82f6',
            fontSize: '12px',
            fontFamily: settings?.dyslexiaMode ? 'Lexend, sans-serif' : 'Outfit, sans-serif',
          },
          securityLevel: 'loose',
        });

        const uniqueId = `mermaid-${Date.now()}`;
        
        mermaid.render(uniqueId, diagram)
          .then(({ svg }) => {
            if (isMounted && elementRef.current) {
              elementRef.current.innerHTML = svg;
            }
          })
          .catch((err) => {
            console.error("Mermaid rendering error:", err);
            if (isMounted && elementRef.current) {
              elementRef.current.innerHTML = `
                <div class="text-3xs text-rose-500 font-semibold p-3 bg-rose-50 dark:bg-rose-950/10 border border-rose-100 dark:border-rose-900/20 rounded-xl">
                  Could not load concept diagram. Please ask Deeta to redraw.
                </div>
              `;
            }
          });
      } catch (err) {
        console.error("Failed to initialize or render mermaid:", err);
      }
    }

    return () => {
      isMounted = false;
    };
  }, [diagram, settings]);

  if (!diagram) return null;

  return (
    <div className="bg-white dark:bg-darkCard border border-zinc-200 dark:border-zinc-800 rounded-3xl p-6 shadow-sm flex flex-col">
      
      {/* Title */}
      <div className="flex items-center gap-2 mb-4">
        <Network className="h-5 w-5 text-blue-500" />
        <h3 className={`text-sm font-bold text-zinc-400 dark:text-zinc-500 uppercase tracking-wider ${settings?.dyslexiaMode ? 'dyslexia-font' : 'font-sans'}`}>
          Visual Concept Map
        </h3>
      </div>

      {/* Render Area */}
      <div className="w-full flex justify-center overflow-x-auto bg-white dark:bg-zinc-900 rounded-2xl p-6 border border-zinc-100 dark:border-zinc-800">
        <div 
          ref={elementRef} 
          className="mermaid text-zinc-900 dark:text-zinc-100 flex justify-center items-center scale-95 origin-center w-full min-h-[220px]"
        >
          {diagram}
        </div>
      </div>
      
      <p className="text-3xs text-zinc-400 dark:text-zinc-500 mt-2 text-center">
        Flowchart auto-generated by the Visualizer Agent to display structure
      </p>

    </div>
  );
}
